exclude: |
  (?x)
  ^setup/|/static/description/index\.html$|
  ^README\.md$|
  /static/(src/)?lib/|
  ^docs/_templates/.*\.html$|
  (LICENSE.*|COPYING.*)
default_language_version:
  python: python3
  node: "14.13.0"
repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --expand-star-imports
          - --ignore-init-module-imports
          - --in-place
          - --remove-all-unused-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=88]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1 # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        name: prettier xml
        args: ["--print-width=120"]
        additional_dependencies:
          - prettier@2.2.1
          - "@prettier/plugin-xml@0.12.0"
        files: \.xml$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.8.0
    hooks:
      - id: eslint
        verbose: true
        args:
          - --color
          - --fix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        # exclude autogenerated files
        exclude: /README\.rst$|\.pot?$
      - id: end-of-file-fixer
        # exclude autogenerated files
        exclude: /README\.rst$|\.pot?$
      - id: debug-statements
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
        # exclude files where underlines are not distinguishable from merge conflicts
        exclude: /README\.rst$|^docs/.*\.rst$
      - id: check-symlinks
      - id: check-xml
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
      - id: pyupgrade
        args: ["--keep-percent-format"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort except __init__.py
        args:
          - --settings=.
        exclude: /__init__\.py$
  - repo: https://github.com/PyCQA/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        name: flake8 except __init__.py
        exclude: /__init__\.py$
        additional_dependencies: ["flake8-bugbear==19.8.0"]
      - id: flake8
        name: flake8 only __init__.py
        args: ["--extend-ignore=F401"] # ignore unused imports in __init__.py
        files: /__init__\.py$
        additional_dependencies: ["flake8-bugbear==19.8.0"]
  - repo: https://github.com/OCA/pylint-odoo
    rev: 7.0.2
    hooks:
      - id: pylint_odoo
        name: pylint with optional checks
        args:
          - --rcfile=.pylintrc
          - --exit-zero
        verbose: true
      - id: pylint_odoo
        args:
          - --rcfile=.pylintrc-mandatory
  - repo: https://github.com/oca/maintainer-tools
    rev: ab1d7f6
    hooks:
      - id: oca-gen-addons-table
        stages: [manual] # pre-commit run --hook-stage manual --all
      - id: oca-update-pre-commit-excluded-addons
      - id: oca-fix-manifest-website
        args: ["https://nirun.life/"]
  - repo: https://github.com/acsone/setuptools-odoo
    rev: 2.6.0
    hooks:
      - id: setuptools-odoo-make-default
        stages: [manual]
      - id: setuptools-odoo-get-requirements
        stages: [manual]
        args:
          - --output
          - requirements.txt
          - --header
          - "# generated from manifests external_dependencies"
